import { StyleSheet } from 'react-native';
import { COLORS } from '../config/theme';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  container: { flexGrow: 1, padding: 16, paddingBottom: 28 },
  headerCard: { backgroundColor: COLORS.card, borderRadius: 22, padding: 18, borderWidth: 1, borderColor: COLORS.border, marginBottom: 16 },
  headerTitle: { color: COLORS.secondary, fontSize: 20, fontWeight: '900' },
  headerSubtitle: { color: COLORS.muted, fontSize: 13, marginTop: 4, lineHeight: 18 },
  searchBox: { flexDirection: 'row', marginTop: 16, gap: 10 },
  searchInput: { flex: 1, backgroundColor: COLORS.background, borderRadius: 12, paddingHorizontal: 14, height: 48, borderWidth: 1, borderColor: COLORS.border, color: COLORS.secondary, fontWeight: '700' },
  searchButton: { backgroundColor: COLORS.primary, borderRadius: 12, paddingHorizontal: 16, justifyContent: 'center', alignItems: 'center' },
  searchButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: '800' },
  sectionCard: { backgroundColor: COLORS.card, borderRadius: 20, padding: 16, borderWidth: 1, borderColor: COLORS.border, marginBottom: 14 },
  dateTimeHeader: { flexDirection: 'row', gap: 20 },
  dateTimeBlock: { flex: 1 },
  dateTimeLabel: { color: COLORS.muted, fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  dateTimeValue: { color: COLORS.secondary, fontSize: 15, fontWeight: '800', marginTop: 2 },
  divider: { height: 1, backgroundColor: COLORS.border, marginVertical: 14 },
  sectionTitle: { color: COLORS.secondary, fontSize: 16, fontWeight: '900', marginBottom: 12 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 },
  infoLabel: { color: COLORS.muted, fontSize: 13, fontWeight: '600' },
  infoValue: { color: COLORS.secondary, fontSize: 13, fontWeight: '700' },
  photoGrid: { flexDirection: 'row', gap: 10, marginBottom: 14 },
  photoContainer: { flex: 1, height: 100, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: COLORS.border },
  entryPhoto: { width: '100%', height: '100%' },
  remarksBox: { backgroundColor: '#F8FAFC', padding: 12, borderRadius: 12, borderLeftWidth: 3, borderLeftColor: COLORS.primary },
  remarksLabel: { color: COLORS.primary, fontSize: 11, fontWeight: '800', marginBottom: 2 },
  remarksText: { color: COLORS.secondary, fontSize: 12, lineHeight: 18 },
  dispatchHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  liveBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#BEF264', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8, gap: 5 },
  liveDot: { width: 6, height: 6, borderRadius: 3, backgroundColor: '#3F6212' },
  liveText: { color: '#3F6212', fontSize: 10, fontWeight: '900' },
  dispatchTimeRow: { flexDirection: 'row', gap: 20 },
  dispatchItem: { flex: 1 },
  dispatchLabel: { color: '#0369A1', fontSize: 10, fontWeight: '800', textTransform: 'uppercase' },
  dispatchValue: { color: '#0369A1', fontSize: 16, fontWeight: '900' },
  actionSection: { gap: 10, paddingBottom: 20 },
  confirmButton: { backgroundColor: COLORS.primary, height: 54, borderRadius: 16, justifyContent: 'center', alignItems: 'center', elevation: 2 },
  confirmButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800' },
  cancelButton: { height: 50, borderRadius: 16, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: COLORS.border },
  cancelButtonText: { color: COLORS.muted, fontSize: 14, fontWeight: '700' },
});
